name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Typecheck
        run: bunx tsc --noEmit
      - name: Unit Tests
        run: bun test
      - name: Lint (Biome)
        run: bun run lint
      - name: Build (tsup)
        run: bun run build
      - name: Are the types wrong?
        run: bun attw

  publish:
    needs: checks
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - uses: oven-sh/setup-bun@v1
      - name: Install Dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Publish to NPM
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
